cv.pdf: cv.tex
	pdflatex cv.tex
	rm -f *.ps *.dvi *.aux *.toc *.nav *.snm *.idx *.ind *.ilg *.log *.out *.blg *.bbl
clean:
	rm -f *.ps *.dvi *.aux *.toc *.nav *.snm *.idx *.ind *.ilg *.log *.out *.blg *.bbl
